services:
  - type: web
    name: sentiment-service
    runtime: docker
    plan: free
    region: ohio
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: checksPass
